app/profile/__init__.py
from flask import Blueprint


profile_bp = Blueprint('profile', __name__,
                       template_folder='templates', static_folder='static')


def create_blueprint():
    from . import routes
    return profile_bp

app/profile/routes.py
from flask import render_template, redirect, url_for, flash, request
from app.routes import menu
from . import profile_bp
from flask_login import logout_user, login_required, current_user
from app.forms import ChangePassword, UserForm
from app.models import AirBooking, Flight, Seat, User, Booking, Hotel, Room
from werkzeug.security import generate_password_hash
from app import db
from datetime import datetime


@profile_bp.route('/<username>', methods=['GET', 'POST'])
@login_required
def myaccount(username):
    user = User.query.get_or_404(current_user.id)

    # Установка значений по умолчанию для формы
    form = UserForm(
        gender=user.gender,
        first_name=user.first_name,
        last_name=user.last_name,
        birth_date=user.birth_date.strftime(
            '%Y-%m-%d') if user.birth_date else '',
        email=user.email,
        phone_code=user.phone_code,
        phone_number=user.phone_number
    )

    if request.method == 'POST':
        print("Request form data:", request.form)  # Логирование данных запроса
        if form.validate_on_submit():
            user.gender = form.gender.data
            user.first_name = form.first_name.data
            user.last_name = form.last_name.data

            # Конвертация даты в формат базы данных
            user.birth_date = form.birth_date.data

            user.email = form.email.data
            user.phone_code = form.phone_code.data
            user.phone_number = form.phone_number.data

            db.session.commit()
            flash('User updated successfully', 'success')
            return redirect(url_for('profile.myaccount', username=current_user.username))

        # Вывод ошибок валидации
        if form.errors:
            for field, errors in form.errors.items():
                for error in errors:
                    flash(
                        f"Ошибка в поле {getattr(form, field).label.text}: {error}", 'danger')

    return render_template('myaccount.html', username=username, form=form, user=user, menu=menu, title='Профиль')


@profile_bp.route('/myorders')
@login_required
def myorders():
    orders = Booking.query.filter_by(user_id=current_user.id).all()
    air_orders = AirBooking.query.filter_by(user_id=current_user.id).all()

    combined_orders = []

    for order in orders:
        hotel = Hotel.query.filter_by(id=order.hotel_id).first()
        room = Room.query.filter_by(id=order.room_id).first()
        check_in_date = order.check_in_date if isinstance(
            order.check_in_date, datetime) else datetime.combine(order.check_in_date, datetime.min.time())
        combined_orders.append({
            'type': 'hotel',
            'order': order,
            'hotel': hotel,
            'room': room,
            'date': check_in_date
        })

    for air_order in air_orders:
        first_flight = Flight.query.filter_by(
            id=air_order.first_flight_id).first()
        second_flight = Flight.query.filter_by(
            id=air_order.second_flight_id).first()
        first_return_flight = Flight.query.filter_by(
            id=air_order.first_return_flight_id).first()
        second_return_flight = Flight.query.filter_by(
            id=air_order.second_return_flight_id).first()
        first_seat = Seat.query.filter_by(id=air_order.first_seat_id).first()
        second_seat = Seat.query.filter_by(id=air_order.second_seat_id).first()
        first_return_seat = Seat.query.filter_by(
            id=air_order.first_return_seat_id).first()
        second_return_seat = Seat.query.filter_by(
            id=air_order.second_return_seat_id).first()

        departure_time = first_flight.departure_time if isinstance(
            first_flight.departure_time, datetime) else datetime.combine(first_flight.departure_time, datetime.min.time())
        baggage = Flight.query.filter_by(
            id=air_order.baggage).first()

        combined_orders.append({
            'type': 'air',
            'order': air_order,
            'first_flight': first_flight,
            'second_flight': second_flight,
            'first_return_flight': first_return_flight,
            'second_return_flight': second_return_flight,
            'first_seat': first_seat,
            'second_seat': second_seat,
            'first_return_seat': first_return_seat,
            'second_return_seat': second_return_seat,
            'date': departure_time,
            'baggage': baggage
        })

    combined_orders.sort(key=lambda x: x['date'], reverse=True)

    return render_template('myorders.html', combined_orders=combined_orders, menu=menu, title='Заказы')


@profile_bp.route('/settings', methods=['GET', 'POST'])
@login_required
def settings():
    form = ChangePassword()
    if form.validate_on_submit():
        user = User.query.filter_by(email=current_user.email).first()
        if user.check_password(form.old_password.data):
            user.set_password(form.new_password2.data)
            db.session.commit()
            flash('Вы успешно сменили пароль', 'success')
        else:
            flash('Неверный пароль', 'error')
    return render_template('settings.html', form=form, menu=menu, title='Настройки')


@profile_bp.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('index'))

app/profile/templates/myaccount.html
{% extends 'base.html' %}
{% block content %}
{{ super() }}
<style>
    body{
        overflow: hidden;
    }
</style>
    <div class="delimiter"><h2>Личный кабинет</h2></div>
    <div class="container">
        <div class="sidebar">
            <ul>
                <li class="selected_item"><a href="{{ url_for('profile.myaccount', username=current_user.username) }}">Мой аккаунт</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.myorders') }}">Мои заказы</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.settings') }}">Настройки</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.logout') }}">Выйти из аккаунта</a></li>
            </ul>
        </div>
        <div class="main-content">
            <div class="user-info">
            <form method="post">
                <div  class="user-form" >
                    {{ form.hidden_tag() }}
                    <p>
                        <div class="user-column">
                            <label class="gender_label">{{ form.gender.label }}: </label>
                            {{ form.gender(class="gender_input", id="gender") }}
                            {% for error in form.gender.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </p>
                    <p>
                        <div class="user-column">
                            <label class="first_name_label">{{ form.first_name.label }}</label>
                            <label class="last_name_label">{{ form.last_name.label }}</label>
                            <label class="birth_date_label">{{ form.birth_date.label }}</label>
                        </div>
                        <div class="user-column">
                            {{ form.first_name(class="first_name_input", id="first_name",value= current_user.first_name if current_user.first_name != None else '') }}
                            {% for error in form.first_name.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                            {{ form.last_name(class="last_name_input", id="last_name_series",value=current_user.last_name if current_user.last_name != None else '') }}
                            {% for error in form.last_name.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                            {{ form.birth_date(class="birth_date_input", id="birth_date_series",value=current_user.birth_date) }}
                            {% for error in form.birth_date.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                        </div>
                    </p>
                        <div class="user-column">
                            <label class="email_label">{{ form.email.label }}</label>
                            <label class="phone_code_label">{{ form.phone_code.label }}</label>
                            <label class="phone_number_label_user">{{ form.phone_number.label }}</label>
                        </div>
                        <div class="user-column">
                            {{ form.email(class="email_input", id="email", value=current_user.email, **{'readonly': 'readonly'})|safe }}
                            {% for error in form.email.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                            {{ form.phone_code(class="phone_code_input", id="phone_code",value=current_user.phone_code) }}
                            {% for error in form.phone_code.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                            {{ form.phone_number(class="phone_number_input_user", id="phone_number",value=current_user.phone_number if current_user.phone_number != None else '') }}
                            {% for error in form.phone_number.errors %}
                                <span class="text-danger">{{ error }}</span>
                            {% endfor %}
                            {{ form.submit(class="submit_button_user") }}
                        </div>
                    </p>
                </div>
            </form>
            </div>
        </div>
    </div>
    </script>
{% endblock content %}

app/profile/templates/myorders.html
{% extends 'base.html' %}
{% block content %}
{{ super() }}
    <div class="delimiter"><h2>Личный кабинет</h2></div>
    <div class="container">
        <div class="sidebar">
            <ul>
                <li class="nonselected_item"><a href="{{ url_for('profile.myaccount', username=current_user.username) }}">Мой аккаунт</a></li>
                <li class="selected_item"><a href="{{ url_for('profile.myorders') }}">Мои заказы</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.settings') }}">Настройки</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.logout') }}">Выйти из аккаунта</a></li>
            </ul>
        </div>
        <div class="main-content">
            {% if combined_orders == [] %}
                <div class="empty-cart">
                    <h1>У вас еще нет заказов</h1>
                    <img src="{{ url_for('static', filename='images/empty_cart.png') }}">
                </div>
            {% else %}
                {% for item in combined_orders %}
                    {% if item.type == 'hotel' %}
                        <div class="flexb">
                            <div class="order">
                                <a href="{{ url_for('show_hotel', hotel_id=item.hotel.id) }}">{{ item.hotel.name }}</a>
                                <div class="order_description">
                                    <img src="{{ item.hotel.image_url }}" alt="{{ item.hotel.name }}">
                                    <p>{{ item.hotel.description }}</p>
                                </div>
                                <div class="order_price">
                                    <h2>Цена:</h2>
                                    <div class="order_price_price">
                                        <h3>{{ item.order.total_price }} ₽</h3>
                                    </div>
                                </div>
                            </div>
                            <div class="order_info">
                                <div class="order_status"></div>
                                <div class="profile-hotel-flex">
                                    <h4>Статус:</h4>
                                    <p>{{ item.order.status.name }}</p>
                                </div>
                                <div class="profile-hotel-flex">
                                    <h4>Тип номера:</h4>
                                    <p>{{ item.room.type }}</p>
                                </div>
                                {% for image in item.room.images %}
                                    <a class="images_order" href="{{ image.image_url }}" target="_blank">
                                        <img class="image_order" src="{{ image.image_url }}" alt="Room Photo">
                                    </a>
                                {% endfor %}
                                <div class="profile-hotel-flex">
                                    <h4>Дата заезда:</h4>
                                    <p>{{ item.order.check_in_date }}</p>
                                </div>
                                <div class="profile-hotel-flex">
                                    <h4>Дата выезда:</h4>
                                    <p>{{ item.order.check_out_date }}</p>
                                </div>
                                {% if item.order.status.name == 'Забронирован' %}
                                    <a href="#" class="myButton_order">Оплатить</a>
                                {% endif %}
                            </div>
                        </div>
                    {% elif item.type == 'air' %}
                        <div class="profile-air-order">
                            <div class="profile-air-order-header">
                                <h3>Бронь №{{ item.order.id }}</h3>
                            </div>
                            <div class="profile-air-order-content">
                                <div class="profile-air-flight">
                                    <h4>Рейс туда</h4>
                                    <div class="profile-air-flight-info">
                                        <p>Рейс: {{ item.first_flight.flight_number }}</p>
                                        <p>Откуда: {{ item.first_flight.origin_city.name }}</p>
                                        <p>Куда: {{ item.first_flight.destination_city.name }}</p>
                                        <p>Время отправления: {{ item.first_flight.departure_time }}</p>
                                        <p>Время прибытия: {{ item.first_flight.arrival_time }}</p>
                                        <p>Место: {{ item.first_seat.seat_number }}</p>
                                    </div>
                                    {% if item.second_flight %}
                                    <div class="profile-air-flight-info">
                                        <p>Доп. рейс: {{ item.second_flight.flight_number }}</p>
                                        <p>Откуда: {{ item.second_flight.origin_city.name }}</p>
                                        <p>Куда: {{ item.second_flight.destination_city.name }}</p>
                                        <p>Время отправления: {{ item.second_flight.departure_time }}</p>
                                        <p>Время прибытия: {{ item.second_flight.arrival_time }}</p>
                                        <p>Место: {{ item.second_seat.seat_number }}</p>
                                    </div>
                                    {% endif %}
                                </div>
                                {% if item.first_return_flight %}
                                <div class="profile-air-flight">
                                    <h4>Рейс обратно</h4>
                                    <div class="profile-air-flight-info">
                                        <p>Рейс: {{ item.first_return_flight.flight_number }}</p>
                                        <p>Откуда: {{ item.first_return_flight.origin_city.name }}</p>
                                        <p>Куда: {{ item.first_return_flight.destination_city.name }}</p>
                                        <p>Время отправления: {{ item.first_return_flight.departure_time }}</p>
                                        <p>Время прибытия: {{ item.first_return_flight.arrival_time }}</p>
                                        <p>Место: {{ item.first_return_seat.seat_number }}</p>
                                    </div>
                                    {% if item.second_return_flight %}
                                    <div class="profile-air-flight-info">
                                        <p>Доп. рейс: {{ item.second_return_flight.flight_number }}</p>
                                        <p>Откуда: {{ item.second_return_flight.origin_city.name }}</p>
                                        <p>Куда: {{ item.second_return_flight.destination_city.name }}</p>
                                        <p>Время отправления: {{ item.second_return_flight.departure_time }}</p>
                                        <p>Время прибытия: {{ item.second_return_flight.arrival_time }}</p>
                                        <p>Место: {{ item.second_return_seat.seat_number }}</p>
                                    </div>
                                    {% endif %}
                                </div>
                                {% endif %}
                                <div class="profile-air-order-price">
                                    <div class="air-description">
                                        <div class="profile-air-flex">
                                            <h4>Статус:</h4>
                                            <p class="air-status">{{ item.order.status.name }}</p>
                                        </div>
                                        {% if item.order.baggage %}
                                        <div class="profile-air-flex">
                                            <h4>Багаж:</h4>
                                            <p class="air-status">Да</p>
                                        </div>
                                        {% else %}
                                        <div class="profile-air-flex">
                                            <h4>Багаж:</h4>
                                            <p class="air-status">Нет</p>
                                        </div>
                                        {% endif %}
                                        <div class="profile-air-flex">
                                            <h4>Цена:</h4>
                                            <p class="air-price">{{ item.order.total_price }}</p><p class="air-rubl">₽</p> 
                                        </div>
                                        {% if item.order.status.name == 'Не оплачен' %}
                                            <a href="#" class="myButton_air_order">Оплатить</a>
                                        {% endif %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    {% endif %}
                {% endfor %}
            {% endif %}
        </div>
    </div>
{% endblock content %}

app/profile/templates/profile.html
{% extends 'base.html' %}
{% block content %}
{{ super() }}
    <div class="delimiter"><h2>Личный кабинет</h2></div>
    <div class="container">
        <div class="sidebar">
            <ul>
                <li class="selected_item"><a href="#">Мой аккаунт</a></li>
                <li class="nonselected_item"><a href="#">Мои заказы</a></li>
                <li class="nonselected_item"><a href="#">Настройки</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.logout') }}">Выйти из аккаунта</a></li>
            </ul>
        </div>
        <div class="main-content">
            <p><strong>Username:</strong> {{ current_user.username }}</p>
        <p><strong>Email:</strong> {{ current_user.email }}</p>
        </div>
    </div>
{% endblock content %}

app/profile/templates/settings.html
{% extends 'base.html' %}
{% block content %}
{{ super() }}
<style>
    body{
        overflow: hidden;
    }
</style>
    <div class="delimiter"><h2>Личный кабинет</h2></div>
    <div class="container">
        <div class="sidebar">
            <ul>
                <li class="nonselected_item"><a href="{{ url_for('profile.myaccount',username=current_user.username) }}">Мой аккаунт</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.myorders') }}">Мои заказы</a></li>
                <li class="selected_item"><a href="{{ url_for('profile.settings') }}">Настройки</a></li>
                <li class="nonselected_item"><a href="{{ url_for('profile.logout') }}">Выйти из аккаунта</a></li>
            </ul>
        </div>
        <div class="main-content">
            <form action="" method="post" class="form-contact">
                <p>{{ form.hidden_tag() }}
                    {% for field in form if field.name not in ['csrf_token', 'remember', 'submit'] -%}
                     <p>{{ field.label(class = 'reset_passeord') }}
                     {% if field.errors %}
                               {{ field(class="invalid") }}
                     <span class="invalid-feedback">
                               {% for e in field.errors %}
                               {{ e }}
                               {% endfor %}
                     </span>
                     {% else %}
                               {{ field( class='reset_passeord_window') }}
                     {% endif %}
            {% endfor %}
            <br>{{ form.submit(class="reset_passeord_button",id="submit_reset_password") }}
                {% for cat, msg in get_flashed_messages(True) %}
                <div class="flash-reset {{cat}}">{{msg}}</div>
                {% endfor %} 
            </form>
        </div>
    </div>
{% endblock content %}